### ISSUE TITLE
publish all users

### ISSUE THREAD

**Issue by tarzak** [cwohlman/meteor-users-collection#1]
Hello. If I understand right, the package should create Users collection, but I've got only current user in.

Is this possible, to publish all users in that collection?

**Comment by cwohlman** [comment]
Hi,

The idea of this package is to expose the `Meteor.users` collection as `Users` and add some helpers, you'll need to publish users yourself based what should be visible to the client.

**Comment by cwohlman** [comment]
You can publish users yourself like so:

``` javascript
Meteor.publish('users', function () {
  return Users.find();
});
```

**Comment by tarzak** [comment]
Thanks!

**Comment by cwohlman** [comment]
If you just want to publish users to the client all you need is the accounts-password package and the publish statement I wrote above. 

(Note that the publish statement I wrote is insecure, you'll need to secure it based on your app's requirements)

—

**Comment by tarzak** [comment]
yeah right! it works :). Thanks again.
